### ISSUE TITLE
TODO list

### ISSUE THREAD

**Issue by lpacher** [lpacher/fphd#1]
* [ ] add instructions regarding **HOW TO INSTALL CABLE DRIVERS** on both Linux and Windows
* [ ] improve simulation flows in order to simulate also GL + SDF
* [ ] definitely fix WCFG parsing logic into `realunch.tcl`
* [ ] add support for project-mode batch flow, e.g. `make build [flow=project|noproject] [etc. ]`
* [ ]  save final design checkpoint a `signoff.dcp`
